// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnE7VkbBAlK4Zeb9hktDoO6OL9YoVWcSs',
    appId: '1:738713513125:web:53813e2bcc740c627c314c',
    messagingSenderId: '738713513125',
    projectId: 'sima-rest-api-131bd',
    authDomain: 'sima-rest-api-131bd.firebaseapp.com',
    storageBucket: 'sima-rest-api-131bd.appspot.com',
    measurementId: 'G-EYECXM3P17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG0Y9ljMggSvImFA7tV9Z2uN_Ev5Yq_Ms',
    appId: '1:738713513125:android:7077f0af702e064c7c314c',
    messagingSenderId: '738713513125',
    projectId: 'sima-rest-api-131bd',
    storageBucket: 'sima-rest-api-131bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN-Y_lWH26NsJgsIjg-hCcNUO5c5yybXU',
    appId: '1:738713513125:ios:3966db0d0138649b7c314c',
    messagingSenderId: '738713513125',
    projectId: 'sima-rest-api-131bd',
    storageBucket: 'sima-rest-api-131bd.appspot.com',
    iosBundleId: 'com.example.simaApp',
  );
}
